version: '3.9'

services:

  terraform:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:       
       - BRANCH=${OKTA_TF_BRANCH}
    container_name: automation-terraform
    volumes:
      - ./terraform:/infra
    working_dir: /infra
    command: init -upgrade
    env_file:
      - terraform/env/${TF_WORKSPACE}/.env